//
// ManualTradeBalance.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Balance */
public struct ManualTradeBalance: Codable, JSONEncodable, Hashable {

    public var account: Account?
    public var currency: Currency?
    /** Cash */
    public var cash: Double?

    public init(account: Account? = nil, currency: Currency? = nil, cash: Double? = nil) {
        self.account = account
        self.currency = currency
        self.cash = cash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case currency
        case cash
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(cash, forKey: .cash)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        account = try container.decodeIfPresent(Account.self, forKey: .account)
        currency = try container.decodeIfPresent(Currency.self, forKey: .currency)
        cash = try container.decodeIfPresent(Double.self, forKey: .cash)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("account")
        nonAdditionalPropertyKeys.insert("currency")
        nonAdditionalPropertyKeys.insert("cash")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

