//
// OptionsPlaceOptionStrategyRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OptionsPlaceOptionStrategyRequest: Codable, JSONEncodable, Hashable {

    public var orderType: OrderType
    public var timeInForce: TimeInForceStrict
    /** Trade Price if limit or stop limit order */
    public var price: Double?

    public init(orderType: OrderType, timeInForce: TimeInForceStrict, price: Double? = nil) {
        self.orderType = orderType
        self.timeInForce = timeInForce
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderType = "order_type"
        case timeInForce = "time_in_force"
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderType, forKey: .orderType)
        try container.encode(timeInForce, forKey: .timeInForce)
        try container.encodeIfPresent(price, forKey: .price)
    }
}

