//
// StrategyOrderPlace.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The reponse for a correctly placed order */
public struct StrategyOrderPlace: Codable, JSONEncodable, Hashable {

    public var orderId: Int?
    public var orders: [StrategyOrderPlaceOrdersInner]?

    public init(orderId: Int? = nil, orders: [StrategyOrderPlaceOrdersInner]? = nil) {
        self.orderId = orderId
        self.orders = orders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId
        case orders
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encodeIfPresent(orders, forKey: .orders)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        orderId = try container.decodeIfPresent(Int.self, forKey: .orderId)
        orders = try container.decodeIfPresent([StrategyOrderPlaceOrdersInner].self, forKey: .orders)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("orderId")
        nonAdditionalPropertyKeys.insert("orders")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

