/*
typescript-preserve-allof-description API

A simple API based for testing typescript-preserve-allof-description.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Child } from './child';

/**
 * 
 * @export
 * @interface ResponseChild
 */
export interface ResponseChild {
    /**
     * Description of input Property in ResponseChild schema
     * @type {Child}
     * @memberof ResponseChild
     */
    'input'?: Child;
}

