/*
typescript-preserve-allof-description API

A simple API based for testing typescript-preserve-allof-description.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RequestBody } from './request-body';

/**
 * 
 * @export
 * @interface TestFetchRequest
 */
export interface TestFetchRequest {
    /**
     * Description of input property in RequestBody in Operation
     * @type {RequestBody}
     * @memberof TestFetchRequest
     */
    'input'?: RequestBody;
}

