# coding: utf-8

"""
    FastAPI

    Arbitrarily execute Python code in IPython

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import api_client
from api_client.model.validation_error import ValidationError
from api_client import configuration


class TestValidationError(unittest.TestCase):
    """ValidationError unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
