/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.konfigthis.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-11-06T17:11:34.157-08:00[America/Los_Angeles]")
@Validated
@Tag(name = "healthz", description = "Check to see if API is working")
public interface HealthzApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /healthz : Health check
     *
     * @return Successful health check (status code 200)
     */
    @Operation(
        operationId = "healthzGet",
        summary = "Health check",
        tags = { "ApiStatus" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful health check")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/healthz"
    )
    default ResponseEntity<Void> healthzGet(
        
    ) {
        return new ResponseEntity<>(HttpStatus.OK);
    }

}
