/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  LintingApi,
  SdkApi,
  SpecificationsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { KonfigCustom } from "./client-custom";

export class Konfig extends KonfigCustom {
  readonly linting: LintingApi;
  readonly sdk: SdkApi;
  readonly specifications: SpecificationsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.linting = new LintingApi(configuration);
    this.sdk = new SdkApi(configuration);
    this.specifications = new SpecificationsApi(configuration);
  }

}
