# coding: utf-8

"""
    python-pydantic-response-as-param API

    A simple API based for testing python-pydantic-response-as-param.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Created by: http://example.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from python_pydantic_response_as_param import schemas  # noqa: F401


class Attack(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            monster = schemas.StrSchema
        
            @staticmethod
            def sword() -> typing.Type['Sword']:
                return Sword
            __annotations__ = {
                "monster": monster,
                "sword": sword,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["monster"]) -> MetaOapg.properties.monster: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sword"]) -> 'Sword': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["monster", "sword", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["monster"]) -> typing.Union[MetaOapg.properties.monster, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sword"]) -> typing.Union['Sword', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["monster", "sword", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        monster: typing.Union[MetaOapg.properties.monster, str, schemas.Unset] = schemas.unset,
        sword: typing.Union['Sword', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Attack':
        return super().__new__(
            cls,
            *args,
            monster=monster,
            sword=sword,
            _configuration=_configuration,
            **kwargs,
        )

from python_pydantic_response_as_param.model.sword import Sword
