/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf } from './generate-request-body-additional-generators-value-any-of';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf1 } from './generate-request-body-additional-generators-value-any-of1';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf10 } from './generate-request-body-additional-generators-value-any-of10';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf2 } from './generate-request-body-additional-generators-value-any-of2';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf3 } from './generate-request-body-additional-generators-value-any-of3';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf4 } from './generate-request-body-additional-generators-value-any-of4';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf5 } from './generate-request-body-additional-generators-value-any-of5';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf6 } from './generate-request-body-additional-generators-value-any-of6';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf7 } from './generate-request-body-additional-generators-value-any-of7';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf8 } from './generate-request-body-additional-generators-value-any-of8';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOf9 } from './generate-request-body-additional-generators-value-any-of9';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOfFilesValue } from './generate-request-body-additional-generators-value-any-of-files-value';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidGit } from './generate-request-body-generators-android-git';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidTest } from './generate-request-body-generators-android-test';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsTypescriptAnyOf1ParameterStateInner } from './generate-request-body-generators-typescript-any-of1-parameter-state-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsTypescriptAnyOfPagination } from './generate-request-body-generators-typescript-any-of-pagination';

/**
 * @type GenerateRequestBodyAdditionalGeneratorsValue
 * @export
 */
export type GenerateRequestBodyAdditionalGeneratorsValue = GenerateRequestBodyAdditionalGeneratorsValueAnyOf | GenerateRequestBodyAdditionalGeneratorsValueAnyOf1 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf2 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf3 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf4 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf5 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf6 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf7 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf8 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf9 | GenerateRequestBodyAdditionalGeneratorsValueAnyOf10;


