/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidCopyFilesInner } from './generate-request-body-generators-android-copy-files-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidFilesValue } from './generate-request-body-generators-android-files-value';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidGit } from './generate-request-body-generators-android-git';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidTest } from './generate-request-body-generators-android-test';

/**
 * 
 * @export
 * @interface GenerateRequestBodyGeneratorsKotlin
 */
export interface GenerateRequestBodyGeneratorsKotlin {
    /**
     * 
     * @type {{ [key: string]: GenerateRequestBodyGeneratorsAndroidFilesValue; }}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'files'?: { [key: string]: GenerateRequestBodyGeneratorsAndroidFilesValue; };
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'version': string;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsAndroidGit}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'git': GenerateRequestBodyGeneratorsAndroidGit;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'outputDirectory': string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'readmeSnippet'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'readmeSupportingDescriptionSnippet'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'readmeDescriptionSnippet'?: string;
    /**
     * Configure copying a set of files from a source to a destination. This is useful if you have custom implementations that you would like duplicated across multiple SDK repos.
     * @type {Array<GenerateRequestBodyGeneratorsAndroidCopyFilesInner>}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'copyFiles'?: Array<GenerateRequestBodyGeneratorsAndroidCopyFilesInner>;
    /**
     * Filepath to file containing override for the section in generated documentation for setting up authentication in the SDK.
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'apiDocumentationAuthenticationPartial'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'disabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'defaultTimeout'?: number;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'userAgent'?: string;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsAndroidTest}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'test'?: GenerateRequestBodyGeneratorsAndroidTest;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'language': GenerateRequestBodyGeneratorsKotlinLanguageEnum;
    /**
     * com.acme
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'groupId': string;
    /**
     * acme-kotlin-sdk
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsKotlin
     */
    'artifactId': string;
}

type GenerateRequestBodyGeneratorsKotlinLanguageEnum = 'kotlin'


