/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GenerateRequestBodyGeneratorsAndroidCopyFilesInnerAnyOf
 */
export interface GenerateRequestBodyGeneratorsAndroidCopyFilesInnerAnyOf {
    /**
     * Relative path from directory that contains konfig.yaml to file that you want to copy
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsAndroidCopyFilesInnerAnyOf
     */
    'from': string;
    /**
     * Relative path from directory that contains konfig.yaml to destination you want to copy to
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsAndroidCopyFilesInnerAnyOf
     */
    'to': string;
}

