/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GenerateRequestBodyGeneratorsJavaGitlab
 */
export interface GenerateRequestBodyGeneratorsJavaGitlab {
    /**
     * gitlab.com
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsJavaGitlab
     */
    'domain': string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsJavaGitlab
     */
    'projectId': string;
}

