/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface LintResponseBodyDiagnosisInnerLinePosition
 */
export interface LintResponseBodyDiagnosisInnerLinePosition {
    /**
     * 
     * @type {number}
     * @memberof LintResponseBodyDiagnosisInnerLinePosition
     */
    'start': number;
    /**
     * 
     * @type {number}
     * @memberof LintResponseBodyDiagnosisInnerLinePosition
     */
    'end': number;
}

