/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { LintResponseBodyDiagnosisInner } from './lint-response-body-diagnosis-inner';

/**
 * 
 * @export
 * @interface LintResponseBody
 */
export interface LintResponseBody {
    /**
     * 
     * @type {Array<LintResponseBodyDiagnosisInner>}
     * @memberof LintResponseBody
     */
    'diagnosis': Array<LintResponseBodyDiagnosisInner>;
    /**
     * `true` if no warnings or errors were found while linting else `false`
     * @type {boolean}
     * @memberof LintResponseBody
     */
    'passed': boolean;
}

