# coding: utf-8

"""
    python-pydantic-any-schema-dict-response API

    A simple API based for testing python-pydantic-any-schema-dict-response.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Created by: http://example.com/support
"""

from python_pydantic_any_schema_dict_response.paths.simple_endpoint.get import FetchRaw


class TestApiRaw(
    FetchRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
