/*
NewsCatcher-V3 Production API

Testing SearchApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package newscatcherapi

import (
    "testing"
    "github.com/stretchr/testify/assert"
    "github.com/konfig-dev/newscatcher-go-sdk/go"
)

func Test_newscatcherapi_SearchApiService(t *testing.T) {

    configuration := newscatcherapi.NewConfiguration()
    configuration.SetHost("http://127.0.0.1:4121") 
    configuration.SetApiKey("X_API_TOKEN")
    client := newscatcherapi.NewAPIClient(configuration)

    t.Run("Test SearchApiService Get", func(t *testing.T) {
        request := client.SearchApi.Get(
            "q_example",
        )
        request.PublishedDatePrecision("publishedDatePrecision_example")
        request.SortBy("sortBy_example")
        request.SearchIn("searchIn_example")

        res := request.ExecuteAll()
        assert.Equal(t, 6, len(res))
    })

    t.Run("Test SearchApiService Post", func(t *testing.T) {
        searchRequest := *newscatcherapi.NewSearchRequest(
            "q_example",
        )
        searchRequest.SetPublishedDatePrecision("publishedDatePrecision_example")
        searchRequest.SetSortBy("sortBy_example")
        searchRequest.SetSearchIn("searchIn_example")

        request := client.SearchApi.Post(
            searchRequest,
        )
        res := request.ExecuteAll()
        assert.Equal(t, 6, len(res))
    })
}