/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5.0.0
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Parameters for generating flexible package quotes
 * @export
 * @interface FlexibleServiceRequest
 */
export interface FlexibleServiceRequest {
    /**
     * Date of earliest flexible service quote to generate
     * @type {string}
     * @memberof FlexibleServiceRequest
     */
    'start_date': string;
    /**
     * Date of latest flexible service quote to generate
     * @type {string}
     * @memberof FlexibleServiceRequest
     */
    'end_date': string;
    /**
     * List of hours in local time to generate quotes for: [8, 9, 10, 11, 12]
     * @type {Array<number>}
     * @memberof FlexibleServiceRequest
     */
    'local_hours'?: Array<FlexibleServiceRequestLocalHoursEnum>;
}

type FlexibleServiceRequestLocalHoursEnum = 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20


