/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5.0.0
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * QuoteResponse serializes a Product quote object
 * @export
 * @interface PriceAdjustmentQuoteResponse
 */
export interface PriceAdjustmentQuoteResponse {
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'adjustment_code': string | null;
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'adjustment_family': string | null;
    /**
     * 
     * @type {number}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'adjustment_value': number | null;
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'adjustment_type': string | null;
    /**
     * 
     * @type {number}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'estimated_amount': number | null;
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'adjustment_description': string | null;
    /**
     * 
     * @type {string}
     * @memberof PriceAdjustmentQuoteResponse
     */
    'adjustment_reason': string | null;
}

