/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5.0.0
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type PropertyTypeNullable = 'APARTMENT' | 'COMMERCIAL' | 'OTHER' | 'MULTI_FAMILY_HOME' | 'SINGLE_FAMILY_HOME' | 'STORAGE'

