/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5.0.0
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceType } from './service-type';

/**
 * ServiceWorkers
 * @export
 * @interface ServiceWorkers
 */
export interface ServiceWorkers {
    /**
     * Service Type
     * @type {ServiceType}
     * @memberof ServiceWorkers
     */
    'service_code': ServiceType;
    /**
     * Number of workers
     * @type {number}
     * @memberof ServiceWorkers
     */
    'workers': number;
}

