# coding: utf-8

"""
    python-invalid-response API

    A simple API based for testing python-invalid-response.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Created by: http://example.com/support
"""

from python_invalid_response.paths.dict_instead_of_list_or_scalar.get import DictInsteadOfListOrScalar
from python_invalid_response.paths.invalid_array.get import InvalidArray
from python_invalid_response.paths.invalid_object.get import InvalidObject
from python_invalid_response.paths.invalid_scalar.get import InvalidScalar
from python_invalid_response.paths.list_instead_of_scalar.get import ListInsteadOfScalar
from python_invalid_response.paths.object_instead_of_scalar.get import ObjectInsteadOfScalar
from python_invalid_response.paths.only_one_property_is_invalid.get import OnlyOnePropertyIsInvalid
from python_invalid_response.apis.tags.test_api_raw import TestApiRaw


class TestApi(
    DictInsteadOfListOrScalar,
    InvalidArray,
    InvalidObject,
    InvalidScalar,
    ListInsteadOfScalar,
    ObjectInsteadOfScalar,
    OnlyOnePropertyIsInvalid,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TestApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TestApiRaw(api_client)
