//
// BrowserName.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum BrowserName: String, Codable, CaseIterable {
    case unknown = "Unknown"
    case chrome = "Chrome"
    case firefox = "Firefox"
    case safari = "Safari"
    case edge = "Edge"
    case opera = "Opera"
    case brave = "Brave"
    case vivaldi = "Vivaldi"
    case chromium = "Chromium"
}
