//
// Device.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Device: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var platform: Platform?
    public var web: Web?
    public var mobile: Mobile?

    public init(id: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, platform: Platform? = nil, web: Web? = nil, mobile: Mobile? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.platform = platform
        self.web = web
        self.mobile = mobile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case updatedAt
        case platform
        case web
        case mobile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(web, forKey: .web)
        try container.encodeIfPresent(mobile, forKey: .mobile)
    }
}

