//
// Platform.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Platform: String, Codable, CaseIterable {
    case unknown = "Unknown"
    case mobile = "Mobile"
    case web = "Web"
}
