# coding: utf-8

"""
    splitit-web-api-v3

    Splitit's Web API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from python_splitit_client import PythonSplitit

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        pythonsplitit = PythonSplitit(
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',
        )
        self.assertIsNotNone(pythonsplitit)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
