import React from 'react';
import { Company } from '../../../components/Company';

const sdks = [
  {
    "name": "Authentication",
    "numberOfMethods": 2,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "authentication/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/authentication/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/authentication/openapi.yaml"
  },
  {
    "name": "Authentication",
    "numberOfMethods": 2,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "authentication/python",
    "language": "Python",
    "link": "/sdk/visier/authentication/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/authentication/openapi.yaml"
  },
  {
    "name": "Authentication",
    "numberOfMethods": 2,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "authentication/java",
    "language": "Java",
    "link": "/sdk/visier/authentication/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/authentication/openapi.yaml"
  },
  {
    "name": "ConsolidatedAnalytics",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "consolidated-analytics/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/consolidated-analytics/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/consolidated-analytics/openapi.yaml"
  },
  {
    "name": "ConsolidatedAnalytics",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "consolidated-analytics/python",
    "language": "Python",
    "link": "/sdk/visier/consolidated-analytics/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/consolidated-analytics/openapi.yaml"
  },
  {
    "name": "ConsolidatedAnalytics",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "consolidated-analytics/java",
    "language": "Java",
    "link": "/sdk/visier/consolidated-analytics/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/consolidated-analytics/openapi.yaml"
  },
  {
    "name": "DataHandling",
    "numberOfMethods": 21,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "data-handling/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/data-handling/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/data-handling/openapi.yaml"
  },
  {
    "name": "DataHandling",
    "numberOfMethods": 21,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "data-handling/python",
    "language": "Python",
    "link": "/sdk/visier/data-handling/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/data-handling/openapi.yaml"
  },
  {
    "name": "DataHandling",
    "numberOfMethods": 21,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "data-handling/java",
    "language": "Java",
    "link": "/sdk/visier/data-handling/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/data-handling/openapi.yaml"
  },
  {
    "name": "DataIntake",
    "numberOfMethods": 9,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "data-intake/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/data-intake/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/data-intake/openapi.yaml"
  },
  {
    "name": "DataIntake",
    "numberOfMethods": 9,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "data-intake/python",
    "language": "Python",
    "link": "/sdk/visier/data-intake/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/data-intake/openapi.yaml"
  },
  {
    "name": "DataIntake",
    "numberOfMethods": 9,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "data-intake/java",
    "language": "Java",
    "link": "/sdk/visier/data-intake/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/data-intake/openapi.yaml"
  },
  {
    "name": "DocumentSearch",
    "numberOfMethods": 1,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "document-search/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/document-search/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/document-search/openapi.yaml"
  },
  {
    "name": "DocumentSearch",
    "numberOfMethods": 1,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "document-search/python",
    "language": "Python",
    "link": "/sdk/visier/document-search/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/document-search/openapi.yaml"
  },
  {
    "name": "DocumentSearch",
    "numberOfMethods": 1,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "document-search/java",
    "language": "Java",
    "link": "/sdk/visier/document-search/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/document-search/openapi.yaml"
  },
  {
    "name": "ModelQuery",
    "numberOfMethods": 1,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "model-query/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/model-query/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/model-query/openapi.yaml"
  },
  {
    "name": "ModelQuery",
    "numberOfMethods": 1,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "model-query/python",
    "language": "Python",
    "link": "/sdk/visier/model-query/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/model-query/openapi.yaml"
  },
  {
    "name": "ModelQuery",
    "numberOfMethods": 1,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "model-query/java",
    "language": "Java",
    "link": "/sdk/visier/model-query/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/model-query/openapi.yaml"
  },
  {
    "name": "ObjectConfiguration",
    "numberOfMethods": 6,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "object-configuration/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/object-configuration/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/object-configuration/openapi.yaml"
  },
  {
    "name": "ObjectConfiguration",
    "numberOfMethods": 6,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "object-configuration/python",
    "language": "Python",
    "link": "/sdk/visier/object-configuration/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/object-configuration/openapi.yaml"
  },
  {
    "name": "ObjectConfiguration",
    "numberOfMethods": 6,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "object-configuration/java",
    "language": "Java",
    "link": "/sdk/visier/object-configuration/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/object-configuration/openapi.yaml"
  },
  {
    "name": "PermissionManagement",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "permission-management/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/permission-management/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/permission-management/openapi.yaml"
  },
  {
    "name": "PermissionManagement",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "permission-management/python",
    "language": "Python",
    "link": "/sdk/visier/permission-management/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/permission-management/openapi.yaml"
  },
  {
    "name": "PermissionManagement",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "permission-management/java",
    "language": "Java",
    "link": "/sdk/visier/permission-management/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/permission-management/openapi.yaml"
  },
  {
    "name": "ProfileManagement",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "profile-management/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/profile-management/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/profile-management/openapi.yaml"
  },
  {
    "name": "ProfileManagement",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "profile-management/python",
    "language": "Python",
    "link": "/sdk/visier/profile-management/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/profile-management/openapi.yaml"
  },
  {
    "name": "ProfileManagement",
    "numberOfMethods": 10,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "profile-management/java",
    "language": "Java",
    "link": "/sdk/visier/profile-management/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/profile-management/openapi.yaml"
  },
  {
    "name": "TenantManagement",
    "numberOfMethods": 13,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "tenant-management/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/tenant-management/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/tenant-management/openapi.yaml"
  },
  {
    "name": "TenantManagement",
    "numberOfMethods": 13,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "tenant-management/python",
    "language": "Python",
    "link": "/sdk/visier/tenant-management/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/tenant-management/openapi.yaml"
  },
  {
    "name": "TenantManagement",
    "numberOfMethods": 13,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "tenant-management/java",
    "language": "Java",
    "link": "/sdk/visier/tenant-management/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/tenant-management/openapi.yaml"
  },
  {
    "name": "UserManagement",
    "numberOfMethods": 22,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "user-management/typescript",
    "language": "TypeScript",
    "link": "/sdk/visier/user-management/typescript/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/user-management/openapi.yaml"
  },
  {
    "name": "UserManagement",
    "numberOfMethods": 22,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "user-management/python",
    "language": "Python",
    "link": "/sdk/visier/user-management/python/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/user-management/openapi.yaml"
  },
  {
    "name": "UserManagement",
    "numberOfMethods": 22,
    "categories": [
      "enterprise_software",
      "people_analytics",
      "business_impact",
      "team_management",
      "workforce_insights",
      "human_resources",
      "workforce_intelligence",
      "workforce_analytics",
      "hr_metrics",
      "hr_analytics",
      "hr_dashboard",
      "hr_reporting",
      "workforce_planning",
      "human_capital_management",
      "workforce_solutions",
      "talent_acquisition_analytics"
    ],
    "index": "user-management/java",
    "language": "Java",
    "link": "/sdk/visier/user-management/java/",
    "developerDocumentation": "docs.visier.com/developer/apis/apis.htm",
    "openapiGitHubUi": "https://github.com/konfig-sdks/openapi-examples/tree/HEAD/visier/user-management/openapi.yaml"
  }
];

export default function Visier() {
  const allCategories: string[] = Array.from(
    new Set(sdks.flatMap((service) => service.categories)),
  )
  return (
    <Company
      company="Visier"
      previewLinkImage="https://raw.githubusercontent.com/konfig-sdks/openapi-examples/HEAD/visier/authentication/imagePreview.jpg"
      logo="https://raw.githubusercontent.com/konfig-sdks/openapi-examples/HEAD/visier/authentication/logo.png"
      favicon="https://raw.githubusercontent.com/konfig-sdks/openapi-examples/HEAD/visier/authentication/favicon.png"
      sdks={sdks}
      homepage="visier.com"
      companyKebabCase="visier"
      categories={allCategories}
      metaDescription={`Visier is the people impact platform that puts the right insights in the right hands, at the right time, throughout the business.

We help organizations of all sizes unlock the power of their people data for business impact. This includes enterprises using our category-leading people analytics software, partners embedding our solution into existing apps, and developers building on the Visier platform.

As the global leader in people analytics, Visier has over 25,000 customers in 75 countries around the world, including enterprises like BASF, Bridgestone, Electronic Arts, McKesson, MerckKGaA, and more. Visier is headquartered in Vancouver, BC with offices and team members worldwide.`}
    />
  )
}