/*
 * splitit-web-api-v3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test
{
    /// <summary>
    ///  Class for testing InstallmentPlanGetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstallmentPlanGetResponseTests
    {
        // TODO uncomment below to declare an instance variable for InstallmentPlanGetResponse
        //private InstallmentPlanGetResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InstallmentPlanGetResponse
            //instance = new InstallmentPlanGetResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InstallmentPlanGetResponse
        /// </summary>
        [Test]
        public void InstallmentPlanGetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InstallmentPlanGetResponse
            //Assert.IsInstanceOf(typeof(InstallmentPlanGetResponse), instance);
        }


        /// <summary>
        /// Test the property 'PlanList'
        /// </summary>
        [Test]
        public void PlanListTest()
        {
            // TODO unit test for the property 'PlanList'
        }

    }

}
