/*
 * splitit-web-api-v3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test
{
    /// <summary>
    ///  Class for testing ShippingStatus2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShippingStatus2Tests
    {
        // TODO uncomment below to declare an instance variable for ShippingStatus2
        //private ShippingStatus2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShippingStatus2
            //instance = new ShippingStatus2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShippingStatus2
        /// </summary>
        [Test]
        public void ShippingStatus2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ShippingStatus2
            //Assert.IsInstanceOf(typeof(ShippingStatus2), instance);
        }



    }

}
