openapi: 3.0.3
info:
  title: python-allow-none-for-nullable-ref API
  description: A simple API based for testing python-allow-none-for-nullable-ref.
  version: 1.0.0
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-konfig-ignore:
    object-with-no-properties: true
servers:
  - description: Live API server
    url: https://python-allow-none-for-nullable-ref.konfigthis.com
tags:
  - name: Test
paths:
  /simple-endpoint:
    post:
      tags:
        - Test
      summary: Fetches a JSON value based on input parameter
      operationId: Test_fetch
      description: Provide an input parameter to receive a JSON value with properties.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestFetchResponse'
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    RequestBody:
      type: object
      properties:
        problematic_property:
          type: array
          items:
            $ref: '#/components/schemas/ProblematicSchema'
    ProblematicSchema:
      type: object
      properties:
        nullable_property:
          description: This property is tested to ensure that we can pass a None value
          allOf:
            - $ref: '#/components/schemas/RegularObject'
          deprecated: true
          nullable: true
    RegularObject:
      type: object
      properties:
        regular_property:
          type: string
    TestFetchResponse:
      type: object
      property:
        some_property:
          type: string
security:
  - ApiKey: []
