/* tslint:disable */
/* eslint-disable */
/*
typescript-file-upload-node API

A simple API based for testing typescript-file-upload-node.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/test-api';

