/*
Humanloop API

The Humanloop API allows you to interact with Humanloop from your product or service.

You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.

To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:

```bash
pip install humanloop
```

To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:

```bash
npm i humanloop
```

---

Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).

The version of the OpenAPI document: 4.0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GenericConfigResponse
 */
export interface GenericConfigResponse {
    /**
     * Description of config.
     * @type {string}
     * @memberof GenericConfigResponse
     */
    'description'?: string;
    /**
     * String ID of config. Starts with `config_`.
     * @type {string}
     * @memberof GenericConfigResponse
     */
    'id': string;
    /**
     * Other parameters that define the config.
     * @type {object}
     * @memberof GenericConfigResponse
     */
    'other'?: object;
    /**
     * 
     * @type {string}
     * @memberof GenericConfigResponse
     */
    'type': GenericConfigResponseTypeEnum;
    /**
     * Name of config.
     * @type {string}
     * @memberof GenericConfigResponse
     */
    'name': string;
}

type GenericConfigResponseTypeEnum = 'generic'


