/*
 * Splitit.OnBoarding.Api.V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CurrencyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CurrencyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CurrencyResponse
        //private CurrencyResponse instance;

        public CurrencyResponseTests()
        {
            // TODO uncomment below to create an instance of CurrencyResponse
            //instance = new CurrencyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CurrencyResponse
        /// </summary>
        [Fact]
        public void CurrencyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CurrencyResponse
            //Assert.IsType<CurrencyResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'IsoNumber'
        /// </summary>
        [Fact]
        public void IsoNumberTest()
        {
            // TODO unit test for the property 'IsoNumber'
        }

    }

}
