/*
 * Splitit.OnBoarding.Api.V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test.Model
{
    /// <summary>
    ///  Class for testing GetMerchantResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMerchantResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMerchantResponse
        //private GetMerchantResponse instance;

        public GetMerchantResponseTests()
        {
            // TODO uncomment below to create an instance of GetMerchantResponse
            //instance = new GetMerchantResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMerchantResponse
        /// </summary>
        [Fact]
        public void GetMerchantResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMerchantResponse
            //Assert.IsType<GetMerchantResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LegalName'
        /// </summary>
        [Fact]
        public void LegalNameTest()
        {
            // TODO unit test for the property 'LegalName'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'AnnualSales'
        /// </summary>
        [Fact]
        public void AnnualSalesTest()
        {
            // TODO unit test for the property 'AnnualSales'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'MerchantTempId'
        /// </summary>
        [Fact]
        public void MerchantTempIdTest()
        {
            // TODO unit test for the property 'MerchantTempId'
        }

    }

}
