#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

while read local_ref local_sha remote_ref remote_sha
do
    branch_name=$(echo $remote_ref | sed -E 's/^refs\/heads\///')
    if [ "$branch_name" != "main" ]; then
        # Replace with your specific URL
        curl -X GET "https://changeset-bot.konfigthis.com/api/webhook"
    fi
done

exit 1
