# Generated by Django 5.0.4 on 2024-04-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(
                        related_name="chat", to="chatbot_app.message"
                    ),
                ),
            ],
        ),
    ]
