# Generated by Django 5.0.4 on 2024-04-21 23:52

from django.db import migrations, transaction

def create_initial_space(apps, schema_editor):
    Space = apps.get_model('chatbot_app', 'Space')
    Organization = apps.get_model('chatbot_app', 'Organization')
    with transaction.atomic():
        org = Organization.objects.create(id=1)
        Space.objects.create(id=1, organization=org)

class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0007_organization_space_user_membership"),
    ]

    operations = [
        migrations.RunPython(create_initial_space),
    ]
