# Generated by Django 5.0.4 on 2024-04-22 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0010_alter_membership_user_delete_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="users_in_this_space",
            field=models.ManyToManyField(
                related_name="spaces", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
