# Generated by Django 5.0.4 on 2024-04-22 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0012_remove_space_users_in_this_space_userspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userspace",
            name="space",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_spaces",
                to="chatbot_app.space",
            ),
        ),
        migrations.AlterField(
            model_name="userspace",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
