# Generated by Django 5.0.4 on 2024-04-23 07:12

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Chat = apps.get_model("chatbot_app", "Chat")
    for row in Chat.objects.all():
        row.chat_id = uuid.uuid4()
        row.save(update_fields=["chat_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0020_chat_chat_id"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
