# Generated by Django 5.0.4 on 2024-04-23 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0022_remove_uuid_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurentUserOrganization",
            new_name="CurrentUserOrganization",
        ),
    ]
