# Generated by Django 5.0.4 on 2024-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0023_rename_curentuserorganization_currentuserorganization"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
