# Generated by Django 5.0.4 on 2024-05-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0025_configuration_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="form_data",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="Form",
        ),
    ]
